### ISSUE TITLE
License and copyright information

### ISSUE THREAD

**Issue by mhchem** [brunovcosta/mchemJS#1]
You accidentally removed license and copyright information from the file. This is a license violation and you should fix this. While we are at it, you are also legally required to include "prominent notices stating that You changed the files". You might want to take a look at https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by brunovcosta** [comment]
solved 7c0328f311c15ce966595ddd7fc5273ec2a02323
